### ISSUE TITLE
[UNFI] lambda serverless forwarder does not read multiple s3 subfolders( input type - s3/sqs)

### ISSUE THREAD

**Issue by dharanihj** [elastic/elastic-serverless-forwarder#241] opened 2023-02-13 22:02 UTC
Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
- Steps to Reproduce:
Elastic-Serverless-Forwarder does not ingest from all the sub folders when s3-sqs is the input type.

In the Client environment, they have three folders CloudTrail-Digest, Cloudtrail & CloudTrail-

Issue :  S3 event triggers  --> SQS --> Lambda --> forwards only the files/events from the very first subfolders in s3.

We notice only the events from "CloudTrail-Digest" folders are being ingested. I have not seen even one single event from "CloudTrail" folder yet.
For example,  
- I see the events from only the :                                       Amazon S3 > AWSLogs > folder2 >  aws_account1 >CloudTrail-Digest .
- whereas we also should have seen the event from:  Amazon S3  > AWSLogs > folder2  >  aws_account1 > CloudTrail.

**Comment by tommyers-elastic** [comment] 2023-02-14 16:21
hey @dharanihj , thanks for the bug report. couple things i'd like to check from the customer side if possible:

- could we validate that the content of the SQS messages contain all the objects we expect, to confirm this is a bug in ESF and not in configuration.
- could we validate the s3 event notification configuration to ensure it doesn't have a prefix which limits the events to a single subdirectory?
- are there any permissions differences between the 3 directories which may prevent ESF from accessing the objects within the other 2?
- are there any error logs or otherwise suspicious things coming out of ESF (e.g. APM spans for the missing objects)

thanks!

**Comment by aspacca** [comment] 2023-02-15 05:32
@tommyers-elastic there is indeed a bug, related to integration scope discovery: what we define as ["automatic routing"](https://www.elastic.co/guide/en/observability/current/aws-elastic-serverless-forwarder-configuration.html#aws-serverless-automatic-routing) in the documentation.

my assumption is that when the forwarder parse the CloudTrail s3 objects, it has no information about the fact that he has to extract an events list from the `Records` field.

This information, is at [`ExpandEventListFromField._field_to_expand_event_list_from`](https://github.com/elastic/elastic-serverless-forwarder/blob/main/share/expand_event_list_from_field.py#L21)

`ExpandEventListFromField._field_to_expand_event_list_from` is set according to the value returned from a call to [`expand_event_list_from_field_resolver`](https://github.com/elastic/elastic-serverless-forwarder/blob/main/handlers/aws/utils.py#L501-L508), passing `integration_scope` and `field_to_expand_event_list_from` as parameters

if `integration_scope` is `aws.cloudtrail` we return `Records`, if not we return the value of the `field_to_expand_event_list_from` parameter

`field_to_expand_event_list_from` parameter is the value coming from the [input's `expand_event_list_from_field` setting](https://github.com/elastic/elastic-serverless-forwarder/blob/main/handlers/aws/handler.py#L403).

`integration_scope` parameter is the value coming from [`Input.discover_integration_scope`](https://github.com/elastic/elastic-serverless-forwarder/blob/main/share/config.py#L217-L221), that's finally [`utils.discover_integration_scope`](https://github.com/elastic/elastic-serverless-forwarder/blob/6f089c668e38c16444dd0c82dddc0b41091c0df8/handlers/aws/utils.py#L113) (this indeed might be simplified a little)

in `utils.discover_integration_scope` we find the integration scope according to the [`s3_object_key` value of the first s3 notification in the current sqs record we are processing](https://github.com/elastic/elastic-serverless-forwarder/blob/6f089c668e38c16444dd0c82dddc0b41091c0df8/handlers/aws/utils.py#L125).

the problem is that a single sqs message can [contain multiple s3 notifications](https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html).


the trigger of the lambda in case of an s3 notification to sqs is something like the following:
```
{ "Records": [{ [...], "body": "%JSON of S3 Notification%" }, { [...], "body": "%JSON of S3 Notification%" }]}
```

we correctly look at `Records[N]["body"]` where `N` is the current sqs record
but `Records[N]["body"]`, once parsed as json will look like:
```
{ "Records":[ { [...], "s3":{  [...], "object":{ [...], "key":"object-key-1" } } }, { [...], "s3":{  [...], "object":{ [...], "key":"object-key-2" } } } ] }
```

from this payload we use `Records[0]["s3"]["object"]["key"]`, while we should rather use `Records[N]["s3"]["object"]["key"]`, where `N` must be the current s3 notification we are processing

failing to do so, if the first notification is about a CloudTrail-Digest file and the second notification is about a CloudTrail file, the `integration_scope` will be `aws.cloudtrail-digest` for all of them. chaining up the value we will end with a `ExpandEventListFromField._field_to_expand_event_list_from` that's not set to `Records` for the CloudTrail files

**Comment by aspacca** [comment] 2023-02-15 10:47
> * could we validate that the content of the SQS messages contain all the objects we expect, to confirm this is a bug in ESF and not in configuration.
> * could we validate the s3 event notification configuration to ensure it doesn't have a prefix which limits the events to a single subdirectory?
> * are there any permissions differences between the 3 directories which may prevent ESF from accessing the objects within the other 2?
> * are there any error logs or otherwise suspicious things coming out of ESF (e.g. APM spans for the missing objects)

please, @dharanihj can you still reply to @tommyers-elastic questions?

**Comment by ajmeyers42** [comment] 2023-02-15 16:33
Created SFDC ticket at the request of the customer for collection of customer private information; https://elastic.my.salesforce.com/5008X00002JovnbQAB

**Comment by tommyers-elastic** [comment] 2023-02-16 20:07
Hey all - we shipped v1.7.1 of ESF with a fix for this issue. please let us know if this resolves the issue for UNFI. thanks.

**Comment by dharanihj** [comment] 2023-02-16 21:45
Hi @tommyers-elastic , We will have it deployed in customer environment and keep you posted on the latest.

**Comment by dharanihj** [comment] 2023-02-17 22:34
Hi Team, 

We installed the latest SAR ESF 1.7.1 and looks we still have the same issue as earlier.  We do not see the files/events being ingested from the other 2 folders out of 3 sub folders.

It still is ingesting the events from the very first subfolder in the s3 bucket - named cloudtrail-digest.

**Closed** 2023-08-24 08:12 UTC
Labels: bug
